### ISSUE TITLE
Docker Installation

### ISSUE THREAD

**Issue by gear259** [fastogt/iptv_admin#6]
Please investigate at stage:-
Clone sources:
git clone https://github.com/fastogt/iptv_admin
**cd iptv**
---- receive error of no 'iptv' directory
 
Should this be cd 'iptv_admin'?

**Comment by topilski** [comment]
Hey, when you receive this issue?

**Comment by gear259** [comment]
above issue resolved. However, please see issue following https://github.com/fastogt/iptv_admin/wiki/Docker instruction:

user@pc:~$ cd iptv
user@pc:~/iptv$ git submodule update --init --recursive
Submodule 'cmake' (https://github.com/fastogt/cmake) registered for path 'cmake'
Cloning into '/home/user/iptv/cmake'...
Submodule path 'cmake': checked out 'add0bd2d5ba918c02447c136c34e2b5d1cf22f8d'
**user@pc:~/iptv$ docker-compose up --build -d
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml**

*Error in bold

**Comment by topilski** [comment]
You should be in root of repo.

**Comment by gear259** [comment]
> Hey, when you receive this issue?

as per your wiki it still says to cd to iptv directory but git pulls directory called iptv_admin.  Therefore wiki should be amended to cd /iptv_admin

**Comment by topilski** [comment]
Fixed
