### ISSUE TITLE
Error during ./server.py

### ISSUE THREAD

**Issue by electron64** [fastogt/iptv_admin#8]
Hello i got an error when i try to start the admin panel. I m running ubuntu 18.04.
I installed the server and it s running, i also installed the requirements and mongo db.
Any idea how to fix it please?

`./server.py
Traceback (most recent call last):
  File "./server.py", line 7, in <module>
    from app import app
  File "/home/nono/iptv_admin/app/__init__.py", line 12, in <module>
    from app.service.service_manager import ServiceManager
  File "/home/nono/iptv_admin/app/service/service_manager.py", line 1, in <module>
    from app.common.service.entry import ServiceSettings
ModuleNotFoundError: No module named 'app.common.service'`

**Comment by topilski** [comment]
git submodule update --init --recursive

**Comment by topilski** [comment]
https://github.com/fastogt/iptv_admin/wiki/Build

**Comment by electron64** [comment]
ok thank you.
